name: lab4
services:
  nginx:
    image: "nginx:1.25"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - flask

  flask:
    # image: "maslov_s_a2/flask:1.0"
    build: .
    container_name: flask
    environment:
      # - FLASK_DEBUG=1
      - SQL_DATABASE_TYPE=postgres
      - SQL_USER=maslov_s_a2
      - SQL_PASSWORD=Sergey2005
      - SQL_HOST=postgres
      - SQL_PORT=5432
      - SQL_DATABASE=flask_db
    ports:
      - "5000:5000"
    command: flask --app flask_app run --host=0.0.0.0
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "postgres:16.1-alpine"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Sergey2005
      POSTGRES_USER: maslov_s_a2
      POSTGRES_DB: flask_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d flask_db -U maslov_s_a2"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
